### ISSUE TITLE
TRC-43 - feat: Add global `Colors` theme

### ISSUE THREAD

**Issue by mmcbride2929** [wijohnst/ts_reddit_clone#43]
This feature adds a global color scheme implementation to the project, allowing for a consistent color scheme throughout the entire application. The variables defined in `Colors.scss` can be used in component-specific styles for consistency and modularity.

Create a Styles folder with two files, `Colors.scss` and `Global.scss`. In `Colors.scss,` define a set of colors that will be the project's theme using the `:root` pseudo-class. In `Global.scss`, define global styles for your application, including any styles that reference the colors defined in `Colors.scss`.

The variables defined in `Colors.scss` can now be easily imported and utilized by their respective names in any SCSS file imported after `Global.scss`.

**Comment by wijohnst** [comment]
@mmcbride2929  Is it possible to import `..path/to/Colors.scss` in a global stylesheet and make it accessible in any downstream `.scss` file without requiring additional imports?
